#!/usr/bin/env bash
# Generate db/seeds/ncm.sql from Tabela_NCM_Vigente_<YYYYMMDD>.json.
#
# Usage: db/scripts/ncm-to-sql.sh <json-file> > db/seeds/ncm.sql
#
# Filters the 8-digit leaf codes (e.g. 0101.21.00), strips dots, and emits
# one INSERT row per NCM with the decomposed chapter/heading/subheading.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <ncm-json-file>" >&2
    exit 2
fi

src="$1"
if [ ! -f "$src" ]; then
    echo "file not found: $src" >&2
    exit 1
fi

cat <<'HEADER'
-- Generated by db/scripts/ncm-to-sql.sh — do not edit by hand.
-- Rerun when the Tabela_NCM_Vigente snapshot changes.

BEGIN;
TRUNCATE ncm CASCADE;
HEADER

jq -r '
    def clean:
        gsub("</?i>"; "")                               # strip italic tags around Latin names
        | gsub("^[\\s\\-]+"; "")                        # strip leading dashes/spaces from SH hierarchy markers
        | gsub("\\s+"; " ")                             # collapse whitespace
        | gsub("'"'"'"; "'"'"''"'"'")                  # escape single quotes for SQL
        | sub("\\s+$"; "");

    .Nomenclaturas[]
    | .Codigo as $c
    | ($c | gsub("\\."; "")) as $code
    | select($code | length == 8)
    | [
        $code,
        ($code[0:2]),
        ($code[0:4]),
        ($code[0:6]),
        (.Descricao | clean)
      ]
    | "INSERT INTO ncm (code, chapter, heading, subheading, description) VALUES (\u0027\(.[0])\u0027, \u0027\(.[1])\u0027, \u0027\(.[2])\u0027, \u0027\(.[3])\u0027, \u0027\(.[4])\u0027);"
' "$src"

echo "COMMIT;"
