// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/glwbr/paw/nfce"
)

type PaymentMethod string

const (
	PaymentMethodCash          PaymentMethod = "cash"
	PaymentMethodCheck         PaymentMethod = "check"
	PaymentMethodCreditCard    PaymentMethod = "credit_card"
	PaymentMethodDebitCard     PaymentMethod = "debit_card"
	PaymentMethodStoreCredit   PaymentMethod = "store_credit"
	PaymentMethodFoodVoucher   PaymentMethod = "food_voucher"
	PaymentMethodMealVoucher   PaymentMethod = "meal_voucher"
	PaymentMethodGiftVoucher   PaymentMethod = "gift_voucher"
	PaymentMethodFuelVoucher   PaymentMethod = "fuel_voucher"
	PaymentMethodBankSlip      PaymentMethod = "bank_slip"
	PaymentMethodBankDeposit   PaymentMethod = "bank_deposit"
	PaymentMethodPix           PaymentMethod = "pix"
	PaymentMethodBankTransfer  PaymentMethod = "bank_transfer"
	PaymentMethodLoyaltyCredit PaymentMethod = "loyalty_credit"
	PaymentMethodNoPayment     PaymentMethod = "no_payment"
	PaymentMethodOther         PaymentMethod = "other"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type UnitCode string

const (
	UnitCodeKG      UnitCode = "KG"
	UnitCodeG       UnitCode = "G"
	UnitCodeL       UnitCode = "L"
	UnitCodeML      UnitCode = "ML"
	UnitCodeM       UnitCode = "M"
	UnitCodePC      UnitCode = "PC"
	UnitCodeCX      UnitCode = "CX"
	UnitCodePCT     UnitCode = "PCT"
	UnitCodeDZ      UnitCode = "DZ"
	UnitCodeUNKNOWN UnitCode = "UNKNOWN"
)

func (e *UnitCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitCode(s)
	case string:
		*e = UnitCode(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitCode: %T", src)
	}
	return nil
}

type NullUnitCode struct {
	UnitCode UnitCode `json:"unit_code"`
	Valid    bool     `json:"valid"` // Valid is true if UnitCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitCode) Scan(value interface{}) error {
	if value == nil {
		ns.UnitCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitCode), nil
}

type Receipt struct {
	ID             int64      `json:"id"`
	AccessKey      string     `json:"access_key"`
	Number         int        `json:"number"`
	Series         int        `json:"series"`
	Model          int        `json:"model"`
	IssuedAt       time.Time  `json:"issued_at"`
	AuthProtocol   string     `json:"auth_protocol"`
	Source         string     `json:"source"`
	State          nfce.UF    `json:"state"`
	StoreCnpj      string     `json:"store_cnpj"`
	Subtotal       nfce.Money `json:"subtotal"`
	DiscountAmount nfce.Money `json:"discount_amount"`
	TotalAmount    nfce.Money `json:"total_amount"`
	ApproxTaxTotal nfce.Money `json:"approx_tax_total"`
	ParsedAt       time.Time  `json:"parsed_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type ReceiptItem struct {
	ID               int64               `json:"id"`
	ReceiptID        int64               `json:"receipt_id"`
	Sequence         int                 `json:"sequence"`
	ProductCode      string              `json:"product_code"`
	Description      string              `json:"description"`
	Quantity         nfce.Quantity       `json:"quantity"`
	RawUnit          string              `json:"raw_unit"`
	Unit             nfce.NormalizedUnit `json:"unit"`
	UnitPrice        nfce.Money          `json:"unit_price"`
	TotalPrice       nfce.Money          `json:"total_price"`
	Ncm              *string             `json:"ncm"`
	Cest             string              `json:"cest"`
	Cfop             string              `json:"cfop"`
	GtinCommercial   string              `json:"gtin_commercial"`
	ApproxTaxAmount  nfce.Money          `json:"approx_tax_amount"`
	IcmsRate         *nfce.Rate          `json:"icms_rate"`
	IcmsBaseAmount   *nfce.Money         `json:"icms_base_amount"`
	IcmsAmount       *nfce.Money         `json:"icms_amount"`
	PisRate          *nfce.Rate          `json:"pis_rate"`
	PisBaseAmount    *nfce.Money         `json:"pis_base_amount"`
	PisAmount        *nfce.Money         `json:"pis_amount"`
	CofinsRate       *nfce.Rate          `json:"cofins_rate"`
	CofinsBaseAmount *nfce.Money         `json:"cofins_base_amount"`
	CofinsAmount     *nfce.Money         `json:"cofins_amount"`
}

type ReceiptPayment struct {
	ID        int64              `json:"id"`
	ReceiptID int64              `json:"receipt_id"`
	Method    nfce.PaymentMethod `json:"method"`
	Amount    nfce.Money         `json:"amount"`
}

type Store struct {
	Cnpj       string    `json:"cnpj"`
	Name       string    `json:"name"`
	TradeName  string    `json:"trade_name"`
	StateReg   string    `json:"state_reg"`
	Street     string    `json:"street"`
	Number     string    `json:"number"`
	Complement string    `json:"complement"`
	District   string    `json:"district"`
	City       string    `json:"city"`
	State      string    `json:"state"`
	ZipCode    string    `json:"zip_code"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
