// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipt_items.sql

package db

import (
	"context"

	"github.com/glwbr/paw/nfce"
)

const insertReceiptItem = `-- name: InsertReceiptItem :exec
INSERT INTO receipt_items (
    receipt_id, sequence, product_code, description,
    quantity, raw_unit, unit, unit_price, total_price,
    ncm, cest, cfop, gtin_commercial, approx_tax_amount,
    icms_rate, icms_base_amount, icms_amount,
    pis_rate, pis_base_amount, pis_amount,
    cofins_rate, cofins_base_amount, cofins_amount
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    NULLIF($10::text, ''),
    $11, $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23
)
`

type InsertReceiptItemParams struct {
	ReceiptID        int64               `json:"receipt_id"`
	Sequence         int                 `json:"sequence"`
	ProductCode      string              `json:"product_code"`
	Description      string              `json:"description"`
	Quantity         nfce.Quantity       `json:"quantity"`
	RawUnit          string              `json:"raw_unit"`
	Unit             nfce.NormalizedUnit `json:"unit"`
	UnitPrice        nfce.Money          `json:"unit_price"`
	TotalPrice       nfce.Money          `json:"total_price"`
	NcmCode          string              `json:"ncm_code"`
	Cest             string              `json:"cest"`
	Cfop             string              `json:"cfop"`
	GtinCommercial   string              `json:"gtin_commercial"`
	ApproxTaxAmount  nfce.Money          `json:"approx_tax_amount"`
	IcmsRate         *nfce.Rate          `json:"icms_rate"`
	IcmsBaseAmount   *nfce.Money         `json:"icms_base_amount"`
	IcmsAmount       *nfce.Money         `json:"icms_amount"`
	PisRate          *nfce.Rate          `json:"pis_rate"`
	PisBaseAmount    *nfce.Money         `json:"pis_base_amount"`
	PisAmount        *nfce.Money         `json:"pis_amount"`
	CofinsRate       *nfce.Rate          `json:"cofins_rate"`
	CofinsBaseAmount *nfce.Money         `json:"cofins_base_amount"`
	CofinsAmount     *nfce.Money         `json:"cofins_amount"`
}

func (q *Queries) InsertReceiptItem(ctx context.Context, arg InsertReceiptItemParams) error {
	_, err := q.db.Exec(ctx, insertReceiptItem,
		arg.ReceiptID,
		arg.Sequence,
		arg.ProductCode,
		arg.Description,
		arg.Quantity,
		arg.RawUnit,
		arg.Unit,
		arg.UnitPrice,
		arg.TotalPrice,
		arg.NcmCode,
		arg.Cest,
		arg.Cfop,
		arg.GtinCommercial,
		arg.ApproxTaxAmount,
		arg.IcmsRate,
		arg.IcmsBaseAmount,
		arg.IcmsAmount,
		arg.PisRate,
		arg.PisBaseAmount,
		arg.PisAmount,
		arg.CofinsRate,
		arg.CofinsBaseAmount,
		arg.CofinsAmount,
	)
	return err
}

const listItemsByReceipt = `-- name: ListItemsByReceipt :many
SELECT id, receipt_id, sequence, product_code, description, quantity, raw_unit, unit, unit_price, total_price, ncm, cest, cfop, gtin_commercial, approx_tax_amount, icms_rate, icms_base_amount, icms_amount, pis_rate, pis_base_amount, pis_amount, cofins_rate, cofins_base_amount, cofins_amount FROM receipt_items
WHERE receipt_id = $1
ORDER BY sequence
`

func (q *Queries) ListItemsByReceipt(ctx context.Context, receiptID int64) ([]ReceiptItem, error) {
	rows, err := q.db.Query(ctx, listItemsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptItem{}
	for rows.Next() {
		var i ReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.Sequence,
			&i.ProductCode,
			&i.Description,
			&i.Quantity,
			&i.RawUnit,
			&i.Unit,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.Ncm,
			&i.Cest,
			&i.Cfop,
			&i.GtinCommercial,
			&i.ApproxTaxAmount,
			&i.IcmsRate,
			&i.IcmsBaseAmount,
			&i.IcmsAmount,
			&i.PisRate,
			&i.PisBaseAmount,
			&i.PisAmount,
			&i.CofinsRate,
			&i.CofinsBaseAmount,
			&i.CofinsAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
