// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package db

import (
	"context"
	"time"

	"github.com/glwbr/paw/nfce"
)

const getReceiptByAccessKey = `-- name: GetReceiptByAccessKey :one
SELECT r.id, r.access_key, r.number, r.series, r.model, r.issued_at, r.auth_protocol, r.source, r.state, r.store_cnpj, r.subtotal, r.discount_amount, r.total_amount, r.approx_tax_total, r.parsed_at, r.created_at, s.name AS store_name, s.trade_name AS store_trade_name
FROM receipts r
JOIN stores s ON s.cnpj = r.store_cnpj
WHERE r.access_key = $1
`

type GetReceiptByAccessKeyRow struct {
	ID             int64      `json:"id"`
	AccessKey      string     `json:"access_key"`
	Number         int        `json:"number"`
	Series         int        `json:"series"`
	Model          int        `json:"model"`
	IssuedAt       time.Time  `json:"issued_at"`
	AuthProtocol   string     `json:"auth_protocol"`
	Source         string     `json:"source"`
	State          nfce.UF    `json:"state"`
	StoreCnpj      string     `json:"store_cnpj"`
	Subtotal       nfce.Money `json:"subtotal"`
	DiscountAmount nfce.Money `json:"discount_amount"`
	TotalAmount    nfce.Money `json:"total_amount"`
	ApproxTaxTotal nfce.Money `json:"approx_tax_total"`
	ParsedAt       time.Time  `json:"parsed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	StoreName      string     `json:"store_name"`
	StoreTradeName string     `json:"store_trade_name"`
}

func (q *Queries) GetReceiptByAccessKey(ctx context.Context, accessKey string) (GetReceiptByAccessKeyRow, error) {
	row := q.db.QueryRow(ctx, getReceiptByAccessKey, accessKey)
	var i GetReceiptByAccessKeyRow
	err := row.Scan(
		&i.ID,
		&i.AccessKey,
		&i.Number,
		&i.Series,
		&i.Model,
		&i.IssuedAt,
		&i.AuthProtocol,
		&i.Source,
		&i.State,
		&i.StoreCnpj,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.ApproxTaxTotal,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.StoreName,
		&i.StoreTradeName,
	)
	return i, err
}

const insertReceipt = `-- name: InsertReceipt :one
INSERT INTO receipts (
    access_key, number, series, model, issued_at, auth_protocol,
    source, state, store_cnpj,
    subtotal, discount_amount, total_amount, approx_tax_total,
    parsed_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13,
    $14
)
ON CONFLICT (access_key) DO NOTHING
RETURNING id
`

type InsertReceiptParams struct {
	AccessKey      string     `json:"access_key"`
	Number         int        `json:"number"`
	Series         int        `json:"series"`
	Model          int        `json:"model"`
	IssuedAt       time.Time  `json:"issued_at"`
	AuthProtocol   string     `json:"auth_protocol"`
	Source         string     `json:"source"`
	State          nfce.UF    `json:"state"`
	StoreCnpj      string     `json:"store_cnpj"`
	Subtotal       nfce.Money `json:"subtotal"`
	DiscountAmount nfce.Money `json:"discount_amount"`
	TotalAmount    nfce.Money `json:"total_amount"`
	ApproxTaxTotal nfce.Money `json:"approx_tax_total"`
	ParsedAt       time.Time  `json:"parsed_at"`
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReceipt,
		arg.AccessKey,
		arg.Number,
		arg.Series,
		arg.Model,
		arg.IssuedAt,
		arg.AuthProtocol,
		arg.Source,
		arg.State,
		arg.StoreCnpj,
		arg.Subtotal,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.ApproxTaxTotal,
		arg.ParsedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listReceiptsByDateRange = `-- name: ListReceiptsByDateRange :many
SELECT id, access_key, number, series, issued_at, state, store_cnpj,
       total_amount, parsed_at
FROM receipts
WHERE issued_at >= $1 AND issued_at < $2
ORDER BY issued_at DESC
LIMIT $3 OFFSET $4
`

type ListReceiptsByDateRangeParams struct {
	IssuedAt   time.Time `json:"issued_at"`
	IssuedAt_2 time.Time `json:"issued_at_2"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListReceiptsByDateRangeRow struct {
	ID          int64      `json:"id"`
	AccessKey   string     `json:"access_key"`
	Number      int        `json:"number"`
	Series      int        `json:"series"`
	IssuedAt    time.Time  `json:"issued_at"`
	State       nfce.UF    `json:"state"`
	StoreCnpj   string     `json:"store_cnpj"`
	TotalAmount nfce.Money `json:"total_amount"`
	ParsedAt    time.Time  `json:"parsed_at"`
}

func (q *Queries) ListReceiptsByDateRange(ctx context.Context, arg ListReceiptsByDateRangeParams) ([]ListReceiptsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listReceiptsByDateRange,
		arg.IssuedAt,
		arg.IssuedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceiptsByDateRangeRow{}
	for rows.Next() {
		var i ListReceiptsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessKey,
			&i.Number,
			&i.Series,
			&i.IssuedAt,
			&i.State,
			&i.StoreCnpj,
			&i.TotalAmount,
			&i.ParsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByStore = `-- name: ListReceiptsByStore :many
SELECT id, access_key, number, series, issued_at, state,
       subtotal, discount_amount, total_amount, approx_tax_total, parsed_at
FROM receipts
WHERE store_cnpj = $1
ORDER BY issued_at DESC
LIMIT $2 OFFSET $3
`

type ListReceiptsByStoreParams struct {
	StoreCnpj string `json:"store_cnpj"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListReceiptsByStoreRow struct {
	ID             int64      `json:"id"`
	AccessKey      string     `json:"access_key"`
	Number         int        `json:"number"`
	Series         int        `json:"series"`
	IssuedAt       time.Time  `json:"issued_at"`
	State          nfce.UF    `json:"state"`
	Subtotal       nfce.Money `json:"subtotal"`
	DiscountAmount nfce.Money `json:"discount_amount"`
	TotalAmount    nfce.Money `json:"total_amount"`
	ApproxTaxTotal nfce.Money `json:"approx_tax_total"`
	ParsedAt       time.Time  `json:"parsed_at"`
}

func (q *Queries) ListReceiptsByStore(ctx context.Context, arg ListReceiptsByStoreParams) ([]ListReceiptsByStoreRow, error) {
	rows, err := q.db.Query(ctx, listReceiptsByStore, arg.StoreCnpj, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceiptsByStoreRow{}
	for rows.Next() {
		var i ListReceiptsByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessKey,
			&i.Number,
			&i.Series,
			&i.IssuedAt,
			&i.State,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.ApproxTaxTotal,
			&i.ParsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiptExistsByAccessKey = `-- name: ReceiptExistsByAccessKey :one
SELECT EXISTS(SELECT 1 FROM receipts WHERE access_key = $1)
`

func (q *Queries) ReceiptExistsByAccessKey(ctx context.Context, accessKey string) (bool, error) {
	row := q.db.QueryRow(ctx, receiptExistsByAccessKey, accessKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
