// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipt_payments.sql

package db

import (
	"context"

	"github.com/glwbr/paw/nfce"
)

const insertReceiptPayment = `-- name: InsertReceiptPayment :exec
INSERT INTO receipt_payments (receipt_id, method, amount)
VALUES ($1, $2, $3)
`

type InsertReceiptPaymentParams struct {
	ReceiptID int64              `json:"receipt_id"`
	Method    nfce.PaymentMethod `json:"method"`
	Amount    nfce.Money         `json:"amount"`
}

func (q *Queries) InsertReceiptPayment(ctx context.Context, arg InsertReceiptPaymentParams) error {
	_, err := q.db.Exec(ctx, insertReceiptPayment, arg.ReceiptID, arg.Method, arg.Amount)
	return err
}

const listPaymentsByReceipt = `-- name: ListPaymentsByReceipt :many
SELECT id, receipt_id, method, amount FROM receipt_payments
WHERE receipt_id = $1
`

func (q *Queries) ListPaymentsByReceipt(ctx context.Context, receiptID int64) ([]ReceiptPayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptPayment{}
	for rows.Next() {
		var i ReceiptPayment
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.Method,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
