// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package db

import (
	"context"
)

const getStoreByCNPJ = `-- name: GetStoreByCNPJ :one
SELECT cnpj, name, trade_name, state_reg, street, number, complement, district, city, state, zip_code, created_at, updated_at FROM stores WHERE cnpj = $1
`

func (q *Queries) GetStoreByCNPJ(ctx context.Context, cnpj string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByCNPJ, cnpj)
	var i Store
	err := row.Scan(
		&i.Cnpj,
		&i.Name,
		&i.TradeName,
		&i.StateReg,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStore = `-- name: UpsertStore :exec
INSERT INTO stores (
    cnpj, name, trade_name, state_reg,
    street, number, complement, district, city, state, zip_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (cnpj) DO UPDATE SET
    name       = EXCLUDED.name,
    trade_name = EXCLUDED.trade_name,
    state_reg  = EXCLUDED.state_reg,
    street     = EXCLUDED.street,
    number     = EXCLUDED.number,
    complement = EXCLUDED.complement,
    district   = EXCLUDED.district,
    city       = EXCLUDED.city,
    state      = EXCLUDED.state,
    zip_code   = EXCLUDED.zip_code
`

type UpsertStoreParams struct {
	Cnpj       string `json:"cnpj"`
	Name       string `json:"name"`
	TradeName  string `json:"trade_name"`
	StateReg   string `json:"state_reg"`
	Street     string `json:"street"`
	Number     string `json:"number"`
	Complement string `json:"complement"`
	District   string `json:"district"`
	City       string `json:"city"`
	State      string `json:"state"`
	ZipCode    string `json:"zip_code"`
}

func (q *Queries) UpsertStore(ctx context.Context, arg UpsertStoreParams) error {
	_, err := q.db.Exec(ctx, upsertStore,
		arg.Cnpj,
		arg.Name,
		arg.TradeName,
		arg.StateReg,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.ZipCode,
	)
	return err
}
